/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dluilfwqgjdbhgsdnbfd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsdWlsZndxZ2pkYmhnc2RuYmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxNjkzNzksImV4cCI6MjEwMjc0NTM3OX0.9-0c6MZ8I59NCTyc-KnkJhdE4DNVjO7343oJpjPZNng"